spring:
  profiles:
    active: dev
  application:
    name: customer-service
---
spring:
  config:
    import: optional:configserver:http://localhost:8081
    activate:
      on-profile: dev
  cloud:
    config:
      label: main
      username: root
      password: s3cr3t
  info:
    app:
      name: ${spring.application.name}
      port: ${server.port}
      description: ${application.projectName}
      version: ${application.projectVersion}
      host: ${spring.cloud.client.hostname}