global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['customer-service:8092'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'product-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8091'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'shopping-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['shopping-service:8093'] ## only for demo purposes don't use host.docker.internal in production

